project := group_chat
#CPPFLAGS += -g -D_DEBUG 
CPPFLAGS += -g -D_DEBUG 
CXXFLAGS += -Wfatal-errors
LINKFLAGS := -lzmq -lboost_regex -lboost_thread -lboost_program_options -lboost_chrono -lboost_system

.PHONY:

all: $(project)

include ../common.mk
